export const defaultTournamentData = [
  {
    name: "Group Stage",
    matches: [
      {
        id: "g1",
        team1: { id: "t1", name: "India", flag: "🇮🇳" },
        team2: { id: "t2", name: "Pakistan", flag: "🇵🇰" },
        winner: { id: "t1", name: "India" },
        status: "completed",
        venue: "Melbourne Cricket Ground",
      },
      {
        id: "g2",
        team1: { id: "t3", name: "Australia", flag: "🇦🇺" },
        team2: { id: "t4", name: "South Africa", flag: "🇿🇦" },
        winner: { id: "t3", name: "Australia" },
        status: "completed",
        venue: "Sydney Cricket Ground",
      },
      {
        id: "g3",
        team1: { id: "t5", name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
        team2: { id: "t6", name: "New Zealand", flag: "🇳🇿" },
        winner: { id: "t5", name: "England" },
        status: "completed",
        venue: "Lord's Cricket Ground",
      },
      {
        id: "g4",
        team1: { id: "t7", name: "West Indies", flag: "🇼🇮" },
        team2: { id: "t8", name: "Sri Lanka", flag: "🇱🇰" },
        winner: { id: "t8", name: "Sri Lanka" },
        status: "completed",
        venue: "Arun Jaitley Stadium",
      },
      {
        id: "g5",
        team1: { id: "t9", name: "Bangladesh", flag: "🇧🇩" },
        team2: { id: "t10", name: "Afghanistan", flag: "🇦🇫" },
        winner: { id: "t9", name: "Bangladesh" },
        status: "completed",
        venue: "Eden Gardens",
      },
      {
        id: "g6",
        team1: { id: "t11", name: "Ireland", flag: "🇮🇪" },
        team2: { id: "t12", name: "Netherlands", flag: "🇳🇱" },
        winner: { id: "t11", name: "Ireland" },
        status: "completed",
        venue: "Feroz Shah Kotla",
      },
      {
        id: "g7",
        team1: { id: "t13", name: "Namibia", flag: "🇳🇦" },
        team2: { id: "t14", name: "UAE", flag: "🇦🇪" },
        winner: { id: "t13", name: "Namibia" },
        status: "completed",
        venue: "WACA Ground",
      },
      {
        id: "g8",
        team1: { id: "t15", name: "Kenya", flag: "🇰🇪" },
        team2: { id: "t16", name: "Zimbabwe", flag: "🇿🇼" },
        winner: { id: "t16", name: "Zimbabwe" },
        status: "completed",
        venue: "Old Trafford",
      },
    ],
  },
];

export function convertStagesToBracketRounds(stages) {
  return [
    {
      name: "Round of 16",
      matches: [
        {
          id: "r16-1",
          team1: { id: "t1", name: "India", flag: "🇮🇳" },
          team2: { id: "t2", name: "Pakistan", flag: "🇵🇰" },
          winner: { id: "t1", name: "India" },
          status: "completed",
          venue: "Melbourne Cricket Ground",
        },
        {
          id: "r16-2",
          team1: { id: "t3", name: "Australia", flag: "🇦🇺" },
          team2: { id: "t4", name: "South Africa", flag: "🇿🇦" },
          winner: { id: "t3", name: "Australia" },
          status: "completed",
          venue: "Sydney Cricket Ground",
        },
        {
          id: "r16-3",
          team1: { id: "t5", name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          team2: { id: "t6", name: "New Zealand", flag: "🇳🇿" },
          winner: { id: "t5", name: "England" },
          status: "completed",
          venue: "Lord's Cricket Ground",
        },
        {
          id: "r16-4",
          team1: { id: "t7", name: "West Indies", flag: "🇼🇮" },
          team2: { id: "t8", name: "Sri Lanka", flag: "🇱🇰" },
          winner: { id: "t8", name: "Sri Lanka" },
          status: "completed",
          venue: "Arun Jaitley Stadium",
        },
        {
          id: "r16-5",
          team1: { id: "t9", name: "Bangladesh", flag: "🇧🇩" },
          team2: { id: "t10", name: "Afghanistan", flag: "🇦🇫" },
          winner: { id: "t9", name: "Bangladesh" },
          status: "completed",
          venue: "Eden Gardens",
        },
        {
          id: "r16-6",
          team1: { id: "t11", name: "Ireland", flag: "🇮🇪" },
          team2: { id: "t12", name: "Netherlands", flag: "🇳🇱" },
          winner: { id: "t11", name: "Ireland" },
          status: "completed",
          venue: "Feroz Shah Kotla",
        },
        {
          id: "r16-7",
          team1: { id: "t13", name: "Namibia", flag: "🇳🇦" },
          team2: { id: "t14", name: "UAE", flag: "🇦🇪" },
          winner: { id: "t13", name: "Namibia" },
          status: "completed",
          venue: "WACA Ground",
        },
        {
          id: "r16-8",
          team1: { id: "t15", name: "Kenya", flag: "🇰🇪" },
          team2: { id: "t16", name: "Zimbabwe", flag: "🇿🇼" },
          winner: { id: "t16", name: "Zimbabwe" },
          status: "completed",
          venue: "Old Trafford",
        },
      ],
    },
    {
      name: "Quarter Finals",
      matches: [
        {
          id: "qf1",
          team1: { id: "t1", name: "India", flag: "🇮🇳" },
          team2: { id: "t3", name: "Australia", flag: "🇦🇺" },
          winner: { id: "t1", name: "India" },
          status: "completed",
          venue: "Melbourne Cricket Ground",
        },
        {
          id: "qf2",
          team1: { id: "t5", name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          team2: { id: "t8", name: "Sri Lanka", flag: "🇱🇰" },
          winner: { id: "t5", name: "England" },
          status: "completed",
          venue: "Lord's Cricket Ground",
        },
        {
          id: "qf3",
          team1: { id: "t9", name: "Bangladesh", flag: "🇧🇩" },
          team2: { id: "t11", name: "Ireland", flag: "🇮🇪" },
          winner: { id: "t11", name: "Ireland" },
          status: "completed",
          venue: "Eden Gardens",
        },
        {
          id: "qf4",
          team1: { id: "t13", name: "Namibia", flag: "🇳🇦" },
          team2: { id: "t16", name: "Zimbabwe", flag: "🇿🇼" },
          winner: { id: "t16", name: "Zimbabwe" },
          status: "live",
          venue: "WACA Ground",
        },
      ],
    },
    {
      name: "Semi Finals",
      matches: [
        {
          id: "sf1",
          team1: { id: "t1", name: "India", flag: "🇮🇳" },
          team2: { id: "t5", name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          winner: { id: "t1", name: "India" },
          status: "completed",
          venue: "Narendra Modi Stadium",
        },
        {
          id: "sf2",
          team1: { id: "t11", name: "Ireland", flag: "🇮🇪" },
          team2: { id: "t16", name: "Zimbabwe", flag: "🇿🇼" },
          status: "pending",
          venue: "M. A. Chidambaram Stadium",
        },
      ],
    },
    {
      name: "Finals",
      matches: [
        {
          id: "final",
          team1: { id: "t1", name: "India", flag: "🇮🇳" },
          team2: null,
          status: "pending",
          venue: "Arun Jaitley Stadium",
        },
      ],
    },
  ];
}
